Config: update lexer to match string start
bpftrace/bpftrace pull request #2992
Opened 2024-02-10 02:14 UTC by jordalgo

To prevent this error only match against "config"
keyword if it's the start of the string:

```
bpftrace -e 'struct Foo {int config;} BEGIN { $x = (struct Foo*)0; $x->config; }' -d
stdin:1:56-66: ERROR: syntax error, unexpected config
struct Foo {int config;} BEGIN { $x = (struct Foo*)0; $x->config; }
```

This should be fine since the config block needs
to be at the top and start the line.

##### Checklist

- [ ] Language changes are updated in `man/adoc/bpftrace.adoc` and if needed in `docs/reference_guide.md`
- [ ] User-visible and non-trivial changes updated in `CHANGELOG.md`
- [ ] The new behaviour is covered by tests

2024-02-10 11:43 UTC, ajor requested changes
I probably wasn't clear enough in the original issue description, but it's actually a problem with all reserved keywords, so we'd ideally find a solution that makes them all work in user-defined types.

2024-02-10 12:38 UTC, jordalgo commented
> so we'd ideally find a solution that makes them all work in user-defined types

This change still may be a good temporary solution while we work on one that covers a wider range of keywords, especially if "config" is more common.

2024-02-10 18:50 UTC, danobi commented on src/lexer.l
> +^config                 { return Parser::make_CONFIG(loc); }
Maybe allow leading whitespace too? This would make config blocks whitespace sensitive which (IIUC) is a departure from all other syntax

2024-02-12 10:02 UTC, ajor commented
I don't think it'd be too hard to fix this properly for all keywords: we'd just need to update any rules which should accept user-defined type/field names (such as `type` and `postfix_expr`) to accept "keywords" as well as plain `ident`s, e.g.:

```
keyword:
                config     { $$ = $1; }
        |       if         { $$ = $1; }
        |       while      { $$ = $1; }
                [...]
                ;
postfix_expr:
                [...]
        |       postfix_expr DOT ident      { $$ = new ast::FieldAccess($1, $3, @2); }
        |       postfix_expr DOT keyword    { $$ = new ast::FieldAccess($1, $3, @2); }
```

2024-02-12 12:41 UTC, ajor commented
It'd probably be cleaner to create a new rule along the lines of:
```
external_name: ident | keyword;
```
And then use that in place of `ident` where necessary:
```
postfix_expr:
                [...]
        |       postfix_expr DOT external_name      { $$ = new ast::FieldAccess($1, $3, @2); }
```

2024-02-12 21:18 UTC, jordalgo commented
@ajor Great suggestion! Is something like this what you had in mind? https://github.com/bpftrace/bpftrace/pull/3004

2024-02-12 21:58 UTC, jordalgo commented
Actually, I'm realizing we might just be able to add all the other keywords to the ident definition. All the builtins are there in addition to things like STACK_MODE
```
ident:
                IDENT         { $$ = $1; }
        |       BUILTIN       { $$ = $1; }
        |       CALL          { $$ = $1; }
        |       CALL_BUILTIN  { $$ = $1; }
        |       STACK_MODE    { $$ = $1; }
                ;
 ````

2024-02-13 00:04 UTC, closed without merging