riscv64: testprogs: Fix cc: error: unrecognized command-line option '…
bpftrace/bpftrace pull request #3299
Opened 2024-07-08 07:05 UTC by Rtoax

Compile error on debian12, riscv64:

    $ make
    ...
    [ 59%] Built target runtime_test_files
    [ 59%] Building C object tests/testprogs/CMakeFiles/array_access.dir/array_access.c.o
    cc: error: unrecognized command-line option '-mno-omit-leaf-frame-pointer'; did you mean '-fno-omit-frame-pointer'?
    make[2]: *** [tests/testprogs/CMakeFiles/array_access.dir/build.make:76: tests/testprogs/CMakeFiles/array_access.dir/array_access.c.o] Error 1
    make[1]: *** [CMakeFiles/Makefile2:1925: tests/testprogs/CMakeFiles/array_access.dir/all] Error 2
    make: *** [Makefile:146: all] Error 2

gcc [1] commit 39663298b593 ("RISCV: Add -m(no)-omit-leaf-frame-pointer support.")

    $ git describe 39663298b5934831a0125e12f113ebd83248c3be
    basepoints/gcc-14-2940-g39663298b593

Link: git://gcc.gnu.org/git/gcc.git [1]

2024-07-08 10:41 UTC, ajor approved these changes
Doh - there's always one architecture... Thanks for fixing this!

2024-07-08 10:49 UTC, ajor commented
It looks like Clang 18 has a problem:
```
clang: error: unknown argument: '-fno-omit-frame-pointer -mno-omit-leaf-frame-pointer'
```

2024-07-08 10:54 UTC, ajor requested changes
^

2024-07-10 03:03 UTC, Rtoax commented
> It looks like Clang 18 has a problem:
> 
> ```
> clang: error: unknown argument: '-fno-omit-frame-pointer -mno-omit-leaf-frame-pointer'
> ```

Thanks, i'll try fix this.

2024-07-14 04:24 UTC, Rtoax commented
> It looks like Clang 18 has a problem:
> 
> ```
> clang: error: unknown argument: '-fno-omit-frame-pointer -mno-omit-leaf-frame-pointer'
> ```

I just found a good way to fix this problem, would please review, thanks!

2024-07-15 04:48 UTC, Rtoax commented
I just rebase to master and add `test_and_add_testprog_cflag()` function

2024-07-15 12:48 UTC, ajor approved these changes
Nice! I just fixed up the status message but the PR looks good to me

2024-07-15 13:11 UTC, merged