cmake: Bump max LLVM version to 19
bpftrace/bpftrace pull request #3433
Opened 2024-08-31 18:16 UTC by kraj

##### Checklist

- [ ] Language changes are updated in `man/adoc/bpftrace.adoc`
- [ ] User-visible and non-trivial changes updated in `CHANGELOG.md`
- [ ] The new behaviour is covered by tests

2024-09-02 06:22 UTC, viktormalik reviewed
Do I get it right that this is finally an LLVM release where all we have to do is bump the version? Incredible :open_mouth:

Anyways, I'd prefer if we waited for Nix to add LLVM 19 so that we can run all the tests. Since it should be released tomorrow, it should hopefully not take long before it gets to Nixpkgs.

Also a changelog entry would be nice.

2024-09-03 01:49 UTC, kraj commented
> Do I get it right that this is finally an LLVM release where all we have to do is bump the version? Incredible 😮
> 

yes :)

> Anyways, I'd prefer if we waited for Nix to add LLVM 19 so that we can run all the tests. Since it should be released tomorrow, it should hopefully not take long before it gets to Nixpkgs.

yocto has clang-19 staged already and waiting for final release
https://github.com/kraj/meta-clang/pull/982
and has been testing this patch

> 
> Also a changelog entry would be nice.

OK

2024-09-03 16:10 UTC, danobi commented
LGTM,  but like Viktor said, would be good to wait until we have it in CI until we merge this. Cuz if we merge and we cut a release, might ship a buggy release.

2024-09-03 16:24 UTC, kraj commented
> LGTM, but like Viktor said, would be good to wait until we have it in CI until we merge this. Cuz if we merge and we cut a release, might ship a buggy release.

No issues, sounds reasonable.

2024-09-03 18:39 UTC, danobi approved these changes

2024-09-05 06:40 UTC, viktormalik approved these changes

2024-09-16 12:17 UTC, danobi commented
Looks like `ubuntu:devel` is already on llvm 19. So our distro build fails in CI.

I'm thinking about merging this but gating llvm 19 behind CMAKE_BUILD_TYPE=Debug. Idea is that we don't want llvm 19 built by packagers yet but also want CI working until nix releases llvm 19.

Or we could move CI to track nix unstable. Kinda hesitant to do this b/c nix is kinda a black box for many folks and I'm not sure we want to be debugging weird nix things.

2024-09-16 15:57 UTC, ajor commented
> I'm thinking about merging this but gating llvm 19 behind CMAKE_BUILD_TYPE=Debug. Idea is that we don't want llvm 19 built by packagers yet but also want CI working until nix releases llvm 19.

Sounds like a good idea to me. Also lets people experiment with LLVM 19 before we declare it as officially supported.

2024-12-06 20:21 UTC, viktormalik reviewed
Still missing the CI job in `.github/workflows/ci.yml` 🙂

2024-12-09 21:10 UTC, danobi commented
Needs this patch applied to flake.nix: https://pastes.dxuuu.xyz/z5unr7

2024-12-10 11:00 UTC, viktormalik requested changes

2024-12-10 11:00 UTC, viktormalik commented on .github/workflows/ci.yml
> +          RUN_TESTS: 0
For the sake of limiting the amount of CI jobs, we tend to test all LLVM versions in the `Debug` and all the additional configs (`Release`, Clang, AOT, memleak) with just the latest LLVM.

Could you please do that? In other words, this PR should just add one new job `LLVM 19 Debug` and change LLVM 18->19 in all of the other jobs.

2024-12-11 11:29 UTC, viktormalik commented
> Needs this patch applied to flake.nix: https://pastes.dxuuu.xyz/z5unr7

Still needs this for the LLVM 19 jobs to pass.

2024-12-12 07:13 UTC, viktormalik approved these changes
Thanks!

Finally LLVM 19 support :rocket:

2024-12-12 07:14 UTC, merged