BTF: Handle btf__parse_raw() errors
bpftrace/bpftrace pull request #3451
Opened 2024-09-11 18:04 UTC by gal-pressman

btf__parse_raw() can fail and result in NULL pointer dereference somewhere down the road, check its return value.

Without this, I get a segmentation fault when accidentally passing an incorrect BTF file using BPFTRACE_BTF.

##### Checklist

- [x] Language changes are updated in `man/adoc/bpftrace.adoc`
- [x] User-visible and non-trivial changes updated in `CHANGELOG.md`
- [ ] The new behaviour is covered by tests

2024-09-12 00:26 UTC, danobi requested changes
lgtm, but could you please add a unit test?

There's some helpers in tests/btf_common.h that you can probably reuse or use as inspiration. Maybe a new test file tests/btf.cpp as well.

2024-09-12 16:35 UTC, gal-pressman commented
> lgtm, but could you please add a unit test?
> 
> There's some helpers in tests/btf_common.h that you can probably reuse or use as inspiration. Maybe a new test file tests/btf.cpp as well.

Sorry, haven't coded in C++ for years, and prefer not to unless necessary.
I understand if you prefer not to merge this without a test though.

2024-09-16 12:18 UTC, danobi commented
No worries. I can help write a test.

2024-09-16 13:26 UTC, closed without merging

2024-09-16 13:44 UTC, galpressman commented
Thanks Daniel!