Fix: json formatting for hex values
bpftrace/bpftrace pull request #3475
Opened 2024-09-28 20:36 UTC by amiremohamadi

hex values are not supported in json format, so they should be output as a string when json formatting is selected.

##### Checklist

- [ ] Language changes are updated in `man/adoc/bpftrace.adoc`
- [ ] User-visible and non-trivial changes updated in `CHANGELOG.md`
- [x] The new behaviour is covered by tests

2024-09-29 10:16 UTC, jordalgo approved these changes
LGTM. Thanks for the fix!

2024-09-30 06:05 UTC, viktormalik requested changes
Wouldn't it be better to use a decimal number instead of a hex string? JSON output is mainly used for machine processing and this way, we're forcing users to add additional string parsing into the pipeline.

Blocking the PR until we resolve this.

2024-09-30 10:35 UTC, jordalgo commented
> Wouldn't it be better to use a decimal number instead of a hex string? JSON output is mainly used for machine processing and this way, we're forcing users to add additional string parsing into the pipeline.

Yeah, perhaps this is the better way to go. Though if people want hex, you're adding an additional step into their processing pipeline as well. I don't feel strongly either way.

2024-09-30 11:42 UTC, viktormalik commented
> > Wouldn't it be better to use a decimal number instead of a hex string? JSON output is mainly used for machine processing and this way, we're forcing users to add additional string parsing into the pipeline.
> 
> Yeah, perhaps this is the better way to go. Though if people want hex, you're adding an additional step into their processing pipeline as well. I don't feel strongly either way.

The step is always there unless people want hex strings which doesn't seem like something people usually want (at least I don't see a point in having an "address string" as a value of a pointer unless you want to print it straight away).

2024-09-30 11:43 UTC, viktormalik approved these changes

2024-09-30 11:46 UTC, amiremohamadi commented
actually switching to a decimal number instead of a hex string makes sense to me — as @viktormalik mentioned JSON is mainly used for machine processing.

I've made some updates, could you please take another look please?

@viktormalik 
@jordalgo

2024-09-30 13:25 UTC, jordalgo commented on src/output.cpp
> +  switch (type.GetTy()) {
this is super nitpicky so I won't block but I think perhaps moving the pointer and reference printing out of the base Output class `value_to_str` and putting them (like you have it here) in `TextOutput::value_to_str` so it's clear that there is a difference in the output type.

2024-10-01 10:25 UTC, jordalgo commented on src/output.cpp
>      case Type::timestamp_mode: {
Looking good overall! One last small thing. Can you add `case Type::pointer` and `case Type::reference` right above `timestamp_mode` so the switch is exhaustive and will log a bug if anything tries to call `value_to_str` with these two types on the base class?

2024-10-01 10:59 UTC, jordalgo approved these changes
Thanks for the fix!

2024-10-01 11:00 UTC, merged