Logging: Add HINT log level
bpftrace/bpftrace pull request #3607
Opened 2024-11-26 13:25 UTC by ajor

This can be used to provide suggestions to the user when an error is encountered. For example:
```
ERROR: No match for function: myfunc(int64)
HINT: Candidates:
        myfunc(string)
```

2024-11-26 13:54 UTC, viktormalik approved these changes
Sounds useful.

Do we already have some cases where this could be used (maybe even as a part of this PR)?

2024-11-26 14:22 UTC, ajor commented
> Do we already have some cases where this could be used (maybe even as a part of this PR)?

I'm sure I've wanted it in the past, but I can't remember any of them right now. I'd be happy to add a usage in this PR if someone can think of something!

2024-11-26 15:02 UTC, jordalgo requested changes
Mind updating the coding guidelines?
https://github.com/bpftrace/bpftrace/blob/master/docs/coding_guidelines.md#log-messages

2024-11-26 15:03 UTC, jordalgo commented
I like a hint log message. @ttreyer just added a hint type thing here: https://github.com/bpftrace/bpftrace/pull/3534

2024-11-27 15:18 UTC, ajor commented
Done and done :) 

Also expanded the expected results of a few related tests while I fiddled around in there.

2024-11-27 16:04 UTC, jordalgo approved these changes

2024-11-27 16:34 UTC, danobi approved these changes

2024-11-28 07:06 UTC, viktormalik approved these changes
Nice!

2024-11-28 07:06 UTC, merged